//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezoExperts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int ReplierId { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
