//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezoExperts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Clients = new HashSet<Client>();
            this.Experts = new HashSet<Expert>();
        }
    
        public string Email { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Expert> Experts { get; set; }
    }
}
